#!/bin/bash

function fscan(){
  find / -name .git -type d -not \( -path '*/\.[^g]*' -prune \) -not \( -path '/home/thomass/ansible*' -prune \) 2>/dev/null | sed "s/\/\.git//g" | sort > .gm.db
  echo "found following repositories:"
  while read -r line; do
    echo "$line"
  done < .gm.db
}

function fstatus(){
  while read -r dir; do
    cd "$dir"
    result=$(git status | sed -n '2p')
    if [[ $(echo $result | grep -i commits)  ]]; then
      echo -e "\n\n${dir}\n--------------------------------"
      echo $result
    fi
  done < .gm.db
}

function fpull(){
  while read -r dir; do
    echo -e "\n\n${dir}\n--------------------------------"
    cd "$dir"
    git pull
  done < .gm.db
}

function print_help(){
  echo "call gm with following options:"
  echo "  gm scan	- (re)scans all repositorys on the computer"
  echo "  gm status	- shows the status of all repositories in the database"
  echo "  gm pull	- pulls all repositories in the database"
}

if [[ $1 = 'scan' ]]
  then fscan
elif [[ $1 = 'status' ]]
  then fstatus
elif [[ $1 = 'pull' ]]
  then fpull
else
  print_help
fi
